### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by eromoe** [benoitsteiner/tensorflow-opencl#80]
env:
- win 7  x64
- python3.5 in annoconda

install got error : 

```
(py3) C:\Users\Kasim\Desktop>pip install tf_nightly_gpu-1.head-cp35-cp35m-win_amd64.whl
Processing c:\users\kasim\desktop\tf_nightly_gpu-1.head-cp35-cp35m-win_amd64.whl
Exception:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\py3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "D:\Anaconda3\envs\py3\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "D:\Anaconda3\envs\py3\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "D:\Anaconda3\envs\py3\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "D:\Anaconda3\envs\py3\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "D:\Anaconda3\envs\py3\lib\site-packages\pip\download.py", line 809, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "D:\Anaconda3\envs\py3\lib\site-packages\pip\download.py", line 715, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "D:\Anaconda3\envs\py3\lib\site-packages\pip\utils\__init__.py", line 599, in unpack_file
    flatten=not filename.endswith('.whl')
  File "D:\Anaconda3\envs\py3\lib\site-packages\pip\utils\__init__.py", line 484, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "D:\Anaconda3\envs\py3\lib\zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "D:\Anaconda3\envs\py3\lib\zipfile.py", line 1094, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by tjbortz1s** [comment]
I believe, but don't quote me on this, that the .whl files you see here in the download are just for normal tensorflow.  The readme isn't updated and you have to build from source for it to work.

Your issue is that you need to do "pip install wheel", if I am stumbling about the same issue correctly.  

However, after I got that installed to pip and tried to install the file I get "platform not supported" which makes me suspect the gpu package is looking for an NVIDIA gpu instead of one that supports opencl

I'd love to see more specific instructions added to the readme.  I'm clueless, so I'm having trouble figuring out what to do to get this think installed and running.

Note, though, that I'm very in the dark on this, and hopefully someone who knows what they are talking about can give you a more complete answer.  I was just messing with the .whl file as well, and the above is what I've figured out so far.

Sorry if I'm wrong, and sorry if I am not of much help.
